name: "OpenWrt SDK"
description: "Build OpenWrt packages via the SDK"
author: aparcar
runs:
  using: 'composite'
  steps:
    - run: |
        echo "artifacts_dir=${ARTIFACTS_DIR:-$GITHUB_WORKSPACE}" >> "$GITHUB_OUTPUT"
        echo "feed_dir=${FEED_DIR:-$GITHUB_WORKSPACE}" >> "$GITHUB_OUTPUT"
      shell: bash
      id: inputs
    - run: sudo chown -R 1000:1000 ${{ steps.inputs.outputs.artifacts_dir }} ${{ steps.inputs.outputs.feed_dir }}
      shell: bash
    - run: |
        echo "::group:: Construct builder with docker-container driver"
        docker buildx create --name wrt-sdk-container-builder --driver=docker-container
        docker buildx ls
        echo "::endgroup::"
        echo "::group:: Build docker image for SDK"
        docker build \
          --build-arg CONTAINER --build-arg ARCH \
          --builder=wrt-sdk-container-builder --load \
          --cache-to type=gha,mode=max --cache-from type=gha \
          -t sdk $GITHUB_ACTION_PATH
        echo "::endgroup::"
      shell: bash
    - run: |
        docker run --rm \
          --env BUILD_LOG \
          --env EXTRA_FEEDS \
          --env FEEDNAME \
          --env IGNORE_ERRORS \
          --env KEY_BUILD \
          --env NO_DEFAULT_FEEDS \
          --env NO_REFRESH_CHECK \
          --env NO_SHFMT_CHECK \
          --env PACKAGES \
          --env INDEX \
          --env V \
          -v ${{ steps.inputs.outputs.artifacts_dir }}:/artifacts \
          -v ${{ steps.inputs.outputs.feed_dir }}:/feed \
          sdk
      shell: bash
    - run: sudo chown -R --reference=${{ steps.inputs.outputs.artifacts_dir }}/.. ${{ steps.inputs.outputs.artifacts_dir }}
      shell: bash
      if: always()
    - run: sudo chown -R --reference=${{ steps.inputs.outputs.feed_dir }}/.. ${{ steps.inputs.outputs.feed_dir }}
      shell: bash
      if: always()
